# Generated by Django 5.0.6 on 2026-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FloodInundationTelemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("image_name", models.CharField(blank=True, max_length=255, null=True)),
                ("strategy_applied", models.CharField(max_length=150)),
                ("surface_water_confirmed_pct", models.FloatField()),
                ("computed_depth_cm", models.FloatField()),
                ("system_confidence_score_pct", models.FloatField()),
                ("safety_risk_assessment", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "Flood Inundation Telemetry Records",
                "ordering": ["-timestamp"],
            },
        ),
    ]
