# Generated by Django 5.0.6 on 2026-06-21 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_api', '0002_enhanced_temporal_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=120)),
                ('version', models.CharField(db_index=True, max_length=64)),
                ('stage', models.CharField(db_index=True, default='candidate', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('corrected', 'Corrected')], max_length=16)),
                ('corrected_depth_cm', models.FloatField(blank=True, null=True)),
                ('corrected_risk', models.CharField(blank=True, max_length=150)),
                ('reviewer', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='floodinundationtelemetry',
            new_name='flood_api_f_camera__4acbf2_idx',
            old_name='flood_api_f_camera_idx',
        ),
        migrations.RenameIndex(
            model_name='floodinundationtelemetry',
            new_name='flood_api_f_is_wate_1f48c1_idx',
            old_name='flood_api_f_water_idx',
        ),
        migrations.RenameIndex(
            model_name='temporalfloodsequence',
            new_name='flood_api_t_camera__8080fa_idx',
            old_name='flood_api_t_camera_idx',
        ),
        migrations.AddField(
            model_name='cameralocation',
            name='location_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='modelversion',
            unique_together={('model_name', 'version')},
        ),
        migrations.AddField(
            model_name='predictionfeedback',
            name='telemetry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='flood_api.floodinundationtelemetry'),
        ),
    ]
