#!/usr/bin/env python3
"""Generate an HTML gallery for the top-N depth-error images from a readiness report JSON."""
import json
import sys
from pathlib import Path
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('report', help='Path to readiness JSON report')
parser.add_argument('--top', type=int, default=20, help='Top N images')
parser.add_argument('--out', help='Output HTML path', default='reports/top20_errors_gallery.html')
args = parser.parse_args()
report_path = Path(args.report)
if not report_path.exists():
    print('Report not found:', report_path)
    sys.exit(2)

data = json.loads(report_path.read_text(encoding='utf-8'))
rows = data.get('rows', [])

def to_float(v):
    try:
        if v is None: return None
        return float(v)
    except:
        try:
            return float(str(v).strip())
        except:
            return None

errors = []
for r in rows:
    exp = to_float(r.get('expected_depth_cm'))
    ev = to_float(r.get('eval_depth_cm') or r.get('depth_cm'))
    if exp is None or ev is None:
        continue
    ae = abs(ev - exp)
    errors.append((ae, r))
errors.sort(key=lambda x: x[0], reverse=True)
selected = errors[:args.top]

out_path = Path(args.out)
out_path.parent.mkdir(parents=True, exist_ok=True)

html_parts = []
html_parts.append('<!doctype html>')
html_parts.append('<html><head><meta charset="utf-8"><title>Top {} Depth Errors</title>'.format(args.top))
html_parts.append('<style>body{font-family:Arial,Helvetica,sans-serif;padding:12px;background:#fff} .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));grid-gap:12px} .card{border:1px solid #ddd;padding:8px;border-radius:6px;background:#f9fbff} img{max-width:100%;height:auto;display:block;margin:0 auto 6px} .meta{font-size:13px;color:#003366} .k{font-weight:600;color:#0b5394}</style>')
html_parts.append('</head><body>')
html_parts.append('<h2 style="color:#0b5394">Top {} depth absolute errors — generated from {}</h2>'.format(args.top, report_path.name))
html_parts.append('<div class="grid">')
for ae, r in selected:
    img_path = r.get('image_path') or r.get('image')
    # make img_path safe relative
    img_link = img_path.replace('\\','/')
    expected = r.get('expected_depth_cm')
    evald = r.get('eval_depth_cm') if r.get('eval_depth_cm') is not None else r.get('depth_cm')
    pred = r.get('predicted_flood')
    expf = r.get('expected_flood')
    sev = r.get('severity_level')
    wconf = r.get('water_confidence')
    wcov = r.get('water_coverage_pct')
    contradiction = r.get('contradiction')
    notes = r.get('notes') or ''
    card = f'''<div class="card">
<a href="{img_link}" target="_blank"><img src="{img_link}" alt="{r.get('image')}"></a>
<div class="meta"><span class="k">image:</span> {r.get('image')}<br/>
<span class="k">path:</span> <code>{img_path}</code><br/>
<span class="k">expected_depth_cm:</span> {expected} &nbsp;&nbsp; <span class="k">eval_depth_cm:</span> {evald} &nbsp;&nbsp; <span class="k">abs_err:</span> {ae:.2f}<br/>
<span class="k">predicted_flood:</span> {pred} &nbsp;&nbsp; <span class="k">expected_flood:</span> {expf} &nbsp;&nbsp; <span class="k">severity:</span> {sev}<br/>
<span class="k">water_confidence:</span> {wconf} &nbsp;&nbsp; <span class="k">water_coverage_pct:</span> {wcov} &nbsp;&nbsp; <span class="k">contradiction:</span> {contradiction}<br/>
<span class="k">notes:</span> {notes}
</div></div>'''
    html_parts.append(card)

html_parts.append('</div>')
html_parts.append('<p style="font-size:12px;color:#333">Note: Images link to local files; open this HTML in a browser to inspect. Generated by generate_top20_gallery.py</p>')
html_parts.append('</body></html>')

out_path.write_text('\n'.join(html_parts), encoding='utf-8')
print('Wrote', out_path)
print('Open it in your browser to inspect the images.')
