# Generated by Django 5.0.6 on 2026-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_api', '0003_modelversion_predictionfeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=180)),
                ('source_endpoint', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved', '-created_at'], name='flood_api_f_resolve_8db16d_idx'), models.Index(fields=['source_endpoint', '-created_at'], name='flood_api_f_source__fdfbd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=120)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('response_status', models.IntegerField(default=202)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', '-created_at'], name='flood_api_i_endpoin_4241fb_idx')],
            },
        ),
    ]
