# Generated by Django 5.0.6 on 2026-06-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_api', '0004_failedtaskevent_ingestidempotencykey'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('UPLOAD_START', 'Upload Started'), ('UPLOAD_SUCCESS', 'Upload Successful'), ('UPLOAD_FAILED', 'Upload Failed'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_VIEWED', 'Report Viewed'), ('REPORT_DOWNLOADED', 'Report Downloaded')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecureRandomImageUploadResult',
            fields=[
                ('batch_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('scenario_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('camera_id', models.CharField(default='bengaluru_default', max_length=50)),
                ('latitude', models.FloatField(default=13.1939)),
                ('longitude', models.FloatField(default=77.59)),
                ('description', models.TextField(blank=True)),
                ('total_images', models.IntegerField()),
                ('flooded_count', models.IntegerField()),
                ('dry_count', models.IntegerField()),
                ('avg_confidence', models.FloatField()),
                ('avg_depth_cm', models.FloatField()),
                ('max_intensity', models.CharField(choices=[('SAFE', 'Safe - No Flood'), ('MEDIUM', 'Medium - Uncertain'), ('HIGH', 'High - Significant Flood'), ('CRITICAL', 'Critical - Severe Flood')], default='SAFE', max_length=10)),
                ('results_json', models.JSONField()),
                ('report_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Secure Image Upload Result',
                'verbose_name_plural': 'Secure Image Upload Results',
                'db_table': 'secure_random_image_upload_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
